version: '2.2.101'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/Foundation.ObjectService.WebUI.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp2.2/publish
  - cmd: dotnet publish ./src/Foundation.ObjectService.WebUI.csproj
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./tests/Foundation.ObjectService.WebUI.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd tests
  - cmd: dotnet test
deploy: off